version: '3'
services:
  metrics-service-container:
    image: metrics-service-container
    ports:
      - "8080:8080"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    volumes:
      - ./metrics-data:/data/
